### ISSUE TITLE
[Bug]: Error When webui startup and Using civitaibrowser+ searching

### ISSUE THREAD

**Issue by NaughtDZ** [BlafKing/sd-civitai-browser-plus#113]
### Describe the bug.

When webui startup showing error.
Cant search and show error.

### Steps to reproduce the problem.

1. Start webui
2. Serching

### Expected behavior

Should no error

### System info

* Extension version:[6fd4c8c](https://github.com/BlafKing/sd-civitai-browser-plus/commit/6fd4c8c876c61c9e6fcc661014dc0cb464c19a9f)
* OS:Windows 11
* SD-WebUI version:https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7
* Python:3.10.8

### Console logs

```Shell
*** Error running install.py for extension I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus.
*** Command: "I:\stable-diffusion-webui\venv\Scripts\python.exe" "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\install.py"
*** Error code: 1
*** stdout: Installing requirements for CivitAI Browser
***
*** stderr: Traceback (most recent call last):
***   File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\install.py", line 17, in <module>
***     launch.run_pip("install fake_useragent", "requirements for CivitAI Browser")
***   File "I:\stable-diffusion-webui\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "I:\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install requirements for CivitAI Browser.
*** Command: "I:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install fake_useragent --prefer-binary
*** Error code: 1
*** stdout: Collecting fake_useragent
***
*** stderr:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /packages/33/c9/ff44922639b8827dbc86d463d870dabfc19d1567d8a6427dcb2289d83fd8/fake_useragent-1.4.0-py3-none-any.whl.metadata
***   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /packages/33/c9/ff44922639b8827dbc86d463d870dabfc19d1567d8a6427dcb2289d83fd8/fake_useragent-1.4.0-py3-none-any.whl.metadata
***   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /packages/33/c9/ff44922639b8827dbc86d463d870dabfc19d1567d8a6427dcb2289d83fd8/fake_useragent-1.4.0-py3-none-any.whl.metadata
***   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /packages/33/c9/ff44922639b8827dbc86d463d870dabfc19d1567d8a6427dcb2289d83fd8/fake_useragent-1.4.0-py3-none-any.whl.metadata
***   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /packages/33/c9/ff44922639b8827dbc86d463d870dabfc19d1567d8a6427dcb2289d83fd8/fake_useragent-1.4.0-py3-none-any.whl.metadata
*** ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/33/c9/ff44922639b8827dbc86d463d870dabfc19d1567d8a6427dcb2289d83fd8/fake_useragent-1.4.0-py3-none-any.whl.metadata (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
***
***
Launching Web UI with arguments: --autolaunch --xformers --api
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.11.1, num models: 9
*** Error loading script: civitai_api.py
    Traceback (most recent call last):
      File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 17, in <module>
        from fake_useragent import UserAgent
    ModuleNotFoundError: No module named 'fake_useragent'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "I:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "I:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 15, in <module>
        import scripts.civitai_download as _download
      File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 16, in <module>
        import scripts.civitai_api as _api
      File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 19, in <module>
        print(f"{gl.print} Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.")
    AttributeError: module 'scripts.civitai_global' has no attribute 'print'

---
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Aria2 RPC started
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.






-------------------------------------And when serching




Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 512, in update_model_list
    gl.json_data = api_to_data(content_type, sort_type, period_type, use_search_term, current_page, base_filter, only_liked, search_term, nsfw, timeOut, isNext)
  File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 223, in api_to_data
    data = request_civit_api(full_url)
  File "I:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 998, in request_civit_api
    'User-Agent': UserAgent().chrome,
NameError: name 'UserAgent' is not defined
```

**Comment by NaughtDZ** [comment]
Look like Internet issus.Restar my VPN fixed it.

**Comment by BlafKing** [comment]
This error was caused by missing a requirement package. (fake_useragent)
I assumed it failed to download the package since it couldn't connect online, which is why restarting your VPN fixed it.

Looks like it now successfully downloaded the requirement so that automatically fixes the error :)
