### ISSUE TITLE
search fail

### ISSUE THREAD

**Issue by lvyadong199997** [BlafKing/sd-civitai-browser-plus#128]
### Describe the bug.

![1702098014157](https://github.com/BlafKing/sd-civitai-browser-plus/assets/57440775/6b154fb8-b824-4a29-8518-743dd90c926a)

### Steps to reproduce the problem.

 opening stable diffusion and want to search 

### Expected behavior

ERROR

### System info

* Extension version:3ead634e
* OS: Google colab 
* SD-WebUI version: 1.6.1
* Python: python 3.10

### Console logs

```Shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 509, in update_model_list
    gl.json_data = api_to_data(content_type, sort_type, period_type, use_search_term, current_page, base_filter, only_liked, search_term, nsfw, timeOut, isNext)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 208, in api_to_data
    data = request_civit_api(full_url)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 1062, in request_civit_api
    'User-Agent': UserAgent().chrome,
NameError: name 'UserAgent' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 509, in update_model_list
    gl.json_data = api_to_data(content_type, sort_type, period_type, use_search_term, current_page, base_filter, only_liked, search_term, nsfw, timeOut, isNext)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 208, in api_to_data
    data = request_civit_api(full_url)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 1062, in request_civit_api
    'User-Agent': UserAgent().chrome,
NameError: name 'UserAgent' is not defined
```

**Comment by lvyadong199997** [comment]
CivitAI Browser+: Python module 'ZipUnicode' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Aria2 RPC restarted
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'ZipUnicode' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.

**Comment by lvyadong199997** [comment]
I use `pip install fake-useragent`,and it works
