### ISSUE TITLE
[Bug] Civitai crashing on Runpod.io, UserAgent is not defined

### ISSUE THREAD

**Issue by MoreH2000** [BlafKing/sd-civitai-browser-plus#133]
### Describe the bug.

Hello, civitai is giving errors while running on Runpod.io running automatic1111. Here is the error.

```
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 516, in update_model_list
    gl.json_data = api_to_data(content_type, sort_type, period_type, use_search_term, current_page, base_filter, only_liked, search_term, nsfw, timeOut, isNext)
  File "/workspace/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 224, in api_to_data
    data = request_civit_api(full_url)
  File "/workspace/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_api.py", line 1013, in request_civit_api
    'User-Agent': UserAgent().chrome,
NameError: name 'UserAgent' is not defined
```

### Steps to reproduce the problem.

1. Go to automatic1111
2. got to the extension
3. type any model and search

### Expected behavior

The extension should work. It has worked before.

### System info

* Extension version: c0a82f76
* OS: Linux Debian
* SD-WebUI version: v1.6.0
* Python: Python 3.10.12

### Console logs

```Shell
(pasted above)
```

### Additional information

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/29896211/645f7873-4db9-4e37-b10e-41c25cd67a3e)

**Comment by BlafKing** [comment]
You're missing a requirement called `fake-useragent`

Automatic1111 should have installed this when starting the application, but it looks like that has failed for some reason.

You can install it by running: `pip install fake-useragent`

**Comment by MoreH2000** [comment]
Thank you so much. That is exactly what I was missing.

**Comment by BlafKing** [comment]
No problem! :)

**Comment by ElevatedKitten** [comment]
Hey there, I have the exact same problem but doing
`pip install fake-useragent`
wont help. Im new to this whole ordeal, maybe I do something wrong?

**Comment by BlafKing** [comment]
@ElevatedKitten If you can send me your logs then I can have a look what the issue is exactly! :)

**Comment by BlafKing** [comment]
No worries!

I assume this might be caused by multiple python versions/instances being installed.
However, I'm not sure if this is the case since I haven't ever used Runpod before.

If possible, you can try to define the specific python instance that is used by SD-WebUI, and try to install fake-useragent to that instance, I'm not exactly sure where this would be on Linux/Runpod 😅 

I also saw in your log file that you're using `--skip-install`, if you can remove this, then the requirements (including fake-useragent) should be installed automatically when you start SD-WebUI! :)

**Comment by ElevatedKitten** [comment]
@BlafKing Removing `--skip-install` fixed the issue, many thanks!
