### ISSUE TITLE
[Bug]: Installed but without this option

### ISSUE THREAD

**Issue by xdong189** [BlafKing/sd-civitai-browser-plus#148]
### Describe the bug.

It was installed but did not have this TAB.  After many retries, it did not exist

It's really upsetting

### Steps to reproduce the problem.

1. Go to .... 
2. Press ....
3. ...

### Expected behavior

I want that option to be available

### System info

* Extension version:
* OS:win10
* SD-WebUI version:1.7
* Python:3.108

### Console logs

```Shell
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.11.1, num models: 9
CivitAI Browser+: Aria2 RPC started
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
2023-12-26 02:42:31,610 - ControlNet - INFO - ControlNet v1.1.422
ControlNet preprocessor location: E:\AI\novelai-webui-aki-v2\extensions\sd-webui-controlnet\annotator\downloads
2023-12-26 02:42:31,825 - ControlNet - INFO - ControlNet v1.1.422
[sd-webui-freeu] Controlnet support: *enabled*
Image Browser: ImageReward is not installed, cannot be used.
sd-webui-prompt-all-in-one background API service started successfully.
Civitai: API loaded
Loading weights [3e654848b5] from E:\AI\novelai-webui-aki-v2\models\Stable-diffusion\SDM\revAnimated_v122.safetensors
Creating model from config: E:\AI\novelai-webui-aki-v2\configs\v1-inference.yaml
Loading VAE weights specified in settings: E:\AI\novelai-webui-aki-v2\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 7.9s (load weights from disk: 0.8s, create model: 0.6s, apply weights to model: 5.3s, load VAE: 0.7s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.2s).
*** Error executing callback ui_tabs_callback for E:\AI\novelai-webui-aki-v2\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py
    Traceback (most recent call last):
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
        conn = connection.create_connection(
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
        raise err
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
        sock.connect(sa)
    TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
        httplib_response = self._make_request(
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
        self._validate_conn(conn)
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
        conn.connect()
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\connection.py", line 358, in connect
        self.sock = conn = self._new_conn()
      File "E:\AI\novelai-webui-aki-v2\py310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
        raise ConnectTimeoutError(
    urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001DBD07F7850>, 'Connection to civitai.com timed out. (connect timeout=None)')

    During handling of the above exception, another exception occurred:
```

**Comment by BlafKing** [comment]
Thanks for reporting!

The issue you posted should now be fixed in the latest version ([v3.2.2](https://github.com/BlafKing/sd-civitai-browser-plus/commit/e17e5ca6795d61d186706e6a7100372bcc860031))

I'll go ahead and close this bug report since the error should no longer occur but feel free to send another message if you still experience any issues!
