### ISSUE TITLE
[Bug]: Failed at batch downloading LoRas

### ISSUE THREAD

**Issue by CesarCruzUtec** [BlafKing/sd-civitai-browser-plus#163]
### Describe the bug.

While trying to batch download 96 Loras models it gives an error. I was doing the same with other "user name" and it worked perfectly. But when I tried for h_madoka it gives me that error.

### Steps to reproduce the problem.

1. Go to CivitaiBrowser tab
2. Search for h_madoka with the following settings
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/67798431/7d0f706d-621a-4edd-90a5-053c1159c8a3)
3. Press "select all"
4. Press "download all selected"

### Expected behavior

All loras should be downloaded with no error.

### System info

* Extension version: 281cdc0 (last commit)
* OS: Windows 11
* SD-WebUI version: 1.7.0
* Python: 3.10.11

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\IA\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 95, in show_multi_buttons
    if int(model_id) == int(item['model_id']):
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\IA\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\IA\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 152, in selected_to_queue
    model_sha256 = version['files'][0]['hashes']['SHA256']
KeyError: 'SHA256'
```

**Comment by BlafKing** [comment]
Thanks for reporting!

It turns out the "Kama カーマ" model does not have any hashes saved, which this extension did not expect to be a possibility.
I've now published a new version which should still properly handle any downloads if no hashes are saved to the model! :)

I'll go ahead and close this bug report since it should be solved! 👍🏻
