### ISSUE TITLE
[Bug]: Currently an issue with hiding early access LORA

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#182]
### Describe the bug.

This was working fine earlier today, but then suddenly a new search was failing for LORA searches. After disabling "Hide early access models" the search began working again.

Looks like the offending model is probably https://civitai.com/models/284437. It was added shortly before the error started.

### Steps to reproduce the problem.

1.  Weekly LORA search for all LORAs ordered by newest

### Expected behavior

Should not have errored.

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion\automatic1111\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 529, in update_model_list
    HTML = model_list_html(gl.json_data)
  File "C:\stable-diffusion\automatic1111\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 231, in model_list_html
    published_at = datetime.datetime.strptime(version['publishedAt'], "%Y-%m-%dT%H:%M:%S.%fZ")
TypeError: strptime() argument 1 must be str, not None
```

**Comment by khronimo** [comment]
Encountered the same issue.

**Comment by BlafKing** [comment]
Thanks for reporting!

Issue should now be fixed in the latest version! :)
