### ISSUE TITLE
[Bug]:  File permission errors and failed to read errors during update scan

### ISSUE THREAD

**Issue by OuticNZ** [BlafKing/sd-civitai-browser-plus#198]
### Describe the bug.

Receive file permission and failed to read error message during the update process.   The update works fine for a while but will reach a point and start to error.   It's not a permission issue as files are fully accessible.

### Steps to reproduce the problem.

1. Go to Civitai Browser+
2. Press Update Models
3. Select All
4. de-select "Overwrite any existing previews, tags or descriptions"
5. Press "Update model info & tags"

### Expected behavior

It should complete the update without any file permission errors or failed to read errors

### System info

Running SD.Next in docker container with symbolic links mapping model directories to other locations.

* Extension version:   v3.3.1
* OS:  Linux / Unraid
* SD-WebUI version:  Latest
* Python:  3.11.7

### Console logs

```Shell
Traceback (most recent call last):
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/venv/lib/python3.11/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/app/04-SD-Next/webui/extensions/sd-civitai-browser-plus/scripts/civitai_file_manage.py", line 974, in file_scan
    save_model_info(install_path, file_name, sub_folder, preview_html=preview_html, api_response=api_response, overwrite_toggle=overwrite_toggle, from_update=True)
  File "/app/04-SD-Next/webui/extensions/sd-civitai-browser-plus/scripts/civitai_file_manage.py", line 462, in save_model_info
    os.makedirs(install_path)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: 'models/Lora/SD'
```

### Additional information

I did modify the code to workaround the issue by adding additional error handling.  I've since overridden the changes.  I will fork this repo and update and submit a pull request if needed.

**Comment by BlafKing** [comment]
Thanks for reporting!

It's odd that this error is occurring since you stated that the files are fully accessible, but the error message clearly indicates a permission issue.
I don't have much experience with Linux distro's, but I assume that you as a user have file access while the application doesn't have the necessary permissions to create the directory.

I have made merged a new commit with additional error handling, and it now also attempts to get elevated permissions if it initially fails, but this will likely not solve all permission issues.

I wish I could give more insight on how to fix things, but again, I don't know what the approach would be on Linux.

I hope the latest commit fixes most of your issues, but if more permission errors arise, then it's likely not something that can be fixed from within the extension directly.

**Comment by OuticNZ** [comment]
Yeah, it's not a permission issue either.  I'm not quite sure what is causing the issue.  I have a fairly large library of models.

SD.Next is running as userid abc - which has full read-write permissions to the files and directories.  

Will try the update and test.

**Comment by OuticNZ** [comment]
So, assuming this is the version with a fix in it. Version: 665f960f 	2024-02-10 20:58:43

The error isn't occurring now and I can successfully complete a full model info & tag update.

**Comment by BlafKing** [comment]
Awesome, great to hear!

I'll go ahead and close this as resolved 👍🏻
