### ISSUE TITLE
[Bug]: tab disappeared after latest update

### ISSUE THREAD

**Issue by tlandurea** [BlafKing/sd-civitai-browser-plus#212]
### Describe the bug.

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/116924479/cff39e8a-81a3-4337-8790-ba6051dab41a)
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/116924479/09867b52-fae2-48d7-b919-8f8d8239646f)
i did apply and restart and i also tried completely removing and reinstalling it

### Steps to reproduce the problem.

update and restart

### Expected behavior

works

### System info

* Extension version:[7dd32ba3](https://github.com/BlafKing/sd-civitai-browser-plus/commit/7dd32ba38be85df35b2bb8736b983633c43a9313)
* OS:win 10
* SD-WebUI version:
* Python:
version: [v1.7.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cf2772fab0af5573da775e7437e6acdca424f26e)  •  python: 3.10.6

### Console logs

```Shell
*** Error loading script: civitai_api.py
    Traceback (most recent call last):
      File "C:\Users\yeet\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\yeet\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'

---
*** Error loading script: civitai_download.py
    Traceback (most recent call last):
      File "C:\Users\yeet\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\yeet\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 17, in <module>
        import scripts.civitai_api as _api
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'

---
*** Error loading script: civitai_file_manage.py
    Traceback (most recent call last):
      File "C:\Users\yeet\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\yeet\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 20, in <module>
        import scripts.civitai_api as _api
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'

---
*** Error loading script: civitai_gui.py
    Traceback (most recent call last):
      File "C:\Users\yeet\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\yeet\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 12, in <module>
        import scripts.civitai_download as _download
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 17, in <module>
        import scripts.civitai_api as _api
      File "C:\Users\yeet\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'
```

**Comment by BlafKing** [comment]
Didn't properly test the update for the stable version of SD-WebUI, my bad!

Latest hotfix should resolve this issue! :)
