### ISSUE TITLE
[Bug]: `ModuleNotFoundError: No module named 'modules.infotext_utils'` on start

### ISSUE THREAD

**Issue by JUS4HR** [BlafKing/sd-civitai-browser-plus#213]
### Describe the bug.

On webui starts, it tries to import `modules.infotext_utils` but I don't find such script in the `modules` folder.
```ps
> Get-ChildItem F:\ML\stable-diffusion-webui -Name -Depth 10 infotext_utils*
> **returns nothing**
```

### Steps to reproduce the problem.

1. Install via entensions tab
2. Restart Web UI

### Expected behavior

Extension loads properly

### System info

* Extension version: 7dd32ba3 Feb 25 05:45:24 2024
* OS: Windows 11 23H2 22631.3155
* SD-WebUI version: cf2772fa Dec 14 10:03:14 2023
* Python: 3.10.13

### Console logs

```Shell
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --port 5555 --listen --enable-insecure-extension-access --api --cors-allow-origins * --xformers --opt-split-attention --no-half-vae --precision autocast --ckpt-dir ..\SDModels\ckpt --vae-dir ..\SDModels\vae --codeformer-models-path ..\SDModels\codeformer --gfpgan-models-path ..\SDModels\gfpgan --esrgan-models-path ..\SDModels\esrgan --bsrgan-models-path ..\SDModels\bsrgan --realesrgan-models-path ..\SDModels\realesrgan --clip-models-path ..\SDModels\clip --scunet-models-path ..\SDModels\scunet --swinir-models-path ..\SDModels\swinir --ldsr-models-path ..\SDModels\ldsr --lora-dir ..\SDModels\lora --embeddings-dir ..\SDModels\embeddings --hypernetwork-dir ..\SDModels\hypernetwork --textual-inversion-templates-dir ..\SDModels\textual-inversion-templates --lyco-dir ..\SDModels\lyco
Style database not found: F:\ML\stable-diffusion-webui\styles.csv
*** Error loading script: civitai_api.py
    Traceback (most recent call last):
      File "F:\ML\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\ML\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'

---
*** Error loading script: civitai_download.py
    Traceback (most recent call last):
      File "F:\ML\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\ML\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 17, in <module>
        import scripts.civitai_api as _api
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'

---
*** Error loading script: civitai_file_manage.py
    Traceback (most recent call last):
      File "F:\ML\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\ML\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 20, in <module>
        import scripts.civitai_api as _api
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'

---
*** Error loading script: civitai_gui.py
    Traceback (most recent call last):
      File "F:\ML\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\ML\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 12, in <module>
        import scripts.civitai_download as _download
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 17, in <module>
        import scripts.civitai_api as _api
      File "F:\ML\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 16, in <module>
        from modules.infotext_utils import parse_generation_parameters
    ModuleNotFoundError: No module named 'modules.infotext_utils'

---
Loading weights [09ba1e5194] from ..\SDModels\ckpt\_xl_anim_t5.safetensors
2024-02-25 13:18:05,145 - AnimateDiff - INFO - Injecting LCM to UI.
2024-02-25 13:18:05,305 - AnimateDiff - INFO - Hacking i2i-batch.
Creating model from config: F:\ML\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://0.0.0.0:5555

To create a public link, set `share=True` in `launch()`.
Startup time: 9.7s (prepare environment: 1.7s, import torch: 2.2s, import gradio: 1.4s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 1.2s, create ui: 1.3s, gradio launch: 0.2s).
Loading VAE weights specified in settings: ..\SDModels\vae\sdxl_vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 4.3s (load weights from disk: 0.9s, create model: 0.4s, apply weights to model: 2.5s, load VAE: 0.3s, calculate empty prompt: 0.2s).
```

**Comment by BlafKing** [comment]
Turns out this module is only available in the dev branch of SD-WebUI, didn't test that, my bad!

I'll post a hotfix shortly.

**Comment by BlafKing** [comment]
Latest hotfix should now resolve this issue, thanks for notifying me about it! :)
