### ISSUE TITLE
[Bug]: Model Update attribute Error

### ISSUE THREAD

**Issue by RedFoxNightfox** [BlafKing/sd-civitai-browser-plus#214]
### Describe the bug.

updating installed models is producing errors and not functional

### Steps to reproduce the problem.

1. Go to update model and tags information
2. Press  check mark for installed items 
3. Press update model and tags information
4. error.

### Expected behavior

should get info

### System info

* Extension version: latest commit (b069b87)
* OS: Windows 11
* SD-WebUI version: revision cf2772fab0af5573da775e7437e6acdca424f26e (latest)
* Python: 3.10.0

### Console logs

```Shell
Traceback (most recent call last):
  File "M:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "M:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "M:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "M:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "M:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "M:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "M:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "M:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 1022, in file_scan
    preview_html = _api.update_model_info(None, model_versions.get('value'), True, id_value, api_response)
  File "M:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "M:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "M:\Stable-Diffusion\stable-diffusion-webui\modules\generation_parameters_copypaste.py", line 229, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'
```

### Additional information

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/18388478/84cf70ec-e374-44db-8b86-bcbe9edabcdb)

**Comment by RedFoxNightfox** [comment]
seems it was an error on Civitai's end, after trying it several times, it started working again.
