### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by pontius911** [BlafKing/sd-civitai-browser-plus#215]
### Describe the bug.

![Untitled](https://github.com/BlafKing/sd-civitai-browser-plus/assets/11497185/187eb074-9b31-4e69-9d24-eb119a633ddc)

### Steps to reproduce the problem.

1. Go to civid ai browser
2. Press update model
3. Select Checkpoints
4. Press scan for available updates
5. Press load outdated models to browser
6. select outdated SD 1.5 model

### Expected behavior

fore some reason I getting this error when selecting some of SD 1.5 models. Almost all SDXL models I tryed to search worked fine. Some SDXL loras now gives me the same error. the models I found that gives this error are: Harrlogos XL - Finally, custom text generator, RealCartoon-Realistic, RealCartoon - 2.5D, (N)SFW Filter / Slider | Tool LoRA, ClassipeintXL (oil paint / oil painting), Eye - LoRa, Greg Rutkowski Inspired Style LoRA, AnyLoRA - Checkpoint, CuteYukiMix, Laimu / Limealicious (Vtuber), Elden Ring Style, RealCartoon3D, RealCartoon-Pixar, Vixon's Fantasy Mix. those are models I have tested.

### System info

* Extension version:3.4.1
* OS:Windows 11 Pro
* SD-WebUI version:1.7.0
* Python:3.10.9

### Console logs

```Shell
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 428, in update_models_dropdown
    (html, tags, base_mdl, DwnButton, SaveImages, DelButton, filelist, filename, dl_url, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_string, model_versions.get('value'))
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "F:\stable-diffusion-webui-1.7.0\modules\generation_parameters_copypaste.py", line 229, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 428, in update_models_dropdown
    (html, tags, base_mdl, DwnButton, SaveImages, DelButton, filelist, filename, dl_url, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_string, model_versions.get('value'))
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "F:\stable-diffusion-webui-1.7.0\modules\generation_parameters_copypaste.py", line 229, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 428, in update_models_dropdown
    (html, tags, base_mdl, DwnButton, SaveImages, DelButton, filelist, filename, dl_url, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_string, model_versions.get('value'))
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "F:\stable-diffusion-webui-1.7.0\modules\generation_parameters_copypaste.py", line 229, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 428, in update_models_dropdown
    (html, tags, base_mdl, DwnButton, SaveImages, DelButton, filelist, filename, dl_url, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_string, model_versions.get('value'))
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "F:\stable-diffusion-webui-1.7.0\modules\generation_parameters_copypaste.py", line 229, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 428, in update_models_dropdown
    (html, tags, base_mdl, DwnButton, SaveImages, DelButton, filelist, filename, dl_url, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_string, model_versions.get('value'))
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "F:\stable-diffusion-webui-1.7.0\modules\generation_parameters_copypaste.py", line 229, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-1.7.0\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 428, in update_models_dropdown
    (html, tags, base_mdl, DwnButton, SaveImages, DelButton, filelist, filename, dl_url, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_string, model_versions.get('value'))
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "F:\stable-diffusion-webui-1.7.0\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "F:\stable-diffusion-webui-1.7.0\modules\generation_parameters_copypaste.py", line 229, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by ostap667inbox** [comment]
Same problem when clicking on the model info icon on the Extra Network tab:
```
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui-forge\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 433, in model_from_sent
    output_html = _api.update_model_info(None, model_versions.get('value'), True, modelID, json_data)
  File "C:\stable-diffusion-webui-forge\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 804, in update_model_info
    prompt, prompt_dict = image_url_to_promptInfo(image_url)
  File "C:\stable-diffusion-webui-forge\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 653, in image_url_to_promptInfo
    prompt_dict = parse_generation_parameters(prompt)
  File "C:\stable-diffusion-webui-forge\modules\infotext_utils.py", line 255, in parse_generation_parameters
    *lines, lastline = x.strip().split("\n")
AttributeError: 'NoneType' object has no attribute 'strip'

```

**Comment by pontius911** [comment]
another thing I found is if you try to open model info from checkpoint list it gives you "Model ID not found.
Could not locate the model path"

**Comment by BlafKing** [comment]
I assume this happens when a model doesn't have any prompt info, it then encounters an error when the empty prompt is passed to the `parse_generation_parameters` function, which does not expect a None object.
I've added a check so that it only passes it if it's a valid prompt in the latest hotfix!

However, this does not explain why it sometimes works after a few tries, I have submitted this fix for now, but I will do more testing, so please do let me know if you're still encountering issues with the prompt information from example images! :)

**Comment by BlafKing** [comment]
> another thing I found is if you try to open model info from checkpoint list it gives you "Model ID not found. Could not locate the model path"

Also not entirely sure if this is related, regardless I have tried to include a little fix for it, please let me know if this still occurs!

**Comment by pontius911** [comment]
Thanks for your work. all fixed
