### ISSUE TITLE
[Bug]: Can't search any model, "earlyAccessTimeFrame" error

### ISSUE THREAD

**Issue by CesarCruzUtec** [BlafKing/sd-civitai-browser-plus#226]
### Describe the bug.

When trying to search for lora, checkpoint or anything, I get an error

### Steps to reproduce the problem.

1. Go to Civit AI Browser
2. Search Lora by author
3. Press search
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/67798431/46f21bcf-7cca-4695-bdc3-57fb75105641)

### Expected behavior

Show the results and be able to download the models

### System info

* Extension version: [c947679f](https://github.com/BlafKing/sd-civitai-browser-plus/commit/c947679fa48fc756dd53b5e436f7305fe6e1f179)
* OS: Windows 11
* SD-WebUI version: Webui Forge: [f0.0.17v1.8.0rc-latest-276-g29be1da7](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7)
* Python: 3.10.11

### Console logs

```Shell
KeyError: 'earlyAccessTimeFrame'
Traceback (most recent call last):
  File "D:\IA\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\IA\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\IA\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\IA\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\IA\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\IA\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\IA\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\IA\stable-diffusion-webui-forge\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 543, in update_model_list
    HTML = model_list_html(gl.json_data)
  File "D:\IA\stable-diffusion-webui-forge\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 230, in model_list_html
    early_access_days = version['earlyAccessTimeFrame']
KeyError: 'earlyAccessTimeFrame'
```

### Additional information

Yesterday I was able to download as always, it happened today.

**Comment by BlafKing** [comment]
Thanks for reporting!

Looks like there has been an update to the public API and now it no longer contains the `earlyAccessTimeFrame` key.

I'll make sure to find a fix for this shortly and publish a commit with a fix!

**Comment by curiousjp** [comment]
@BlafKing - early access and the api JSON contents generally seem to be a bit of a moving target. I had a look at the raw JSON and for non-early access files at least it seems the whole section is now gone. Seems like a job for `early_access_days = version.get('earlyAccessTimeFrame', 0)` as the minimal fix?

**Comment by BlafKing** [comment]
I've published a new version which includes a fix for this issue!
It turns out early access models have a new key called `earlyAccessDeadline` which defines the date that a model leaves early access, this key only shows up on early access models.

The latest version now uses this key instead to check if a model is still in early access.

Thanks again for notifying me about the issue! I'll mark this as resolved 👍🏻
