### ISSUE TITLE
[Bug]: Download/Update not possible

### ISSUE THREAD

**Issue by DaisukeVN** [BlafKing/sd-civitai-browser-plus#227]
### Describe the bug.

Error after pressing on "Load outdated models to browser".

### Steps to reproduce the problem.

1. Go to CivitAI Browser+
2. Go to Tab "Update Models"
3. Press "All"
4. Press "Scan for available updates"
5. Waiting until Check is done
6. Press "Load outdated models to Browser"
7. Getting Error on Browser Tab and Update Tab

### Expected behavior

Loading the outdated Models to Browser Tab

### System info

* Extension version: 3.4.3
* OS: Win11
* SD-WebUI version: 1.7.0
* Python: 3.10.11

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\Program Files\StableDiffusion\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Program Files\StableDiffusion\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Program Files\StableDiffusion\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Program Files\StableDiffusion\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Program Files\StableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Program Files\StableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Program Files\StableDiffusion\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Program Files\StableDiffusion\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 1139, in load_to_browser
    model_list_return = _api.update_model_list(from_ver=True, tile_count=tile_count)
  File "D:\Program Files\StableDiffusion\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 537, in update_model_list
    HTML = model_list_html(gl.json_data)
  File "D:\Program Files\StableDiffusion\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 235, in model_list_html
    early_access_days = version['earlyAccessTimeFrame']
KeyError: 'earlyAccessTimeFrame'
```

### Additional information

Sometimes this message appears:

The Civit-API has timed out, please try again.
The servers might be too busy or the selected model could not be found."

**Comment by DaisukeVN** [comment]
Okay. Found a "workaround?".
Tick every single categorie works fine. Just "All" is buggy.

**Comment by DaisukeVN** [comment]
> It looks like you're somehow not actually using the latest commit.
> 
> I saw you posted that you're using v3.4.3, but the code indicated by the error: `early_access_days = version['earlyAccessTimeFrame']` No longer exists in this version, so I assume something may have gone wrong with updating?
> 
> Either way, (re)installing the latest version should fix this issue!
> 
> I'll close this bug report, since the bug should already be fixed, But feel free to post any other questions related to the issue 👍🏻

I tried reinstalling it manually (delete the folder and copy new files downloaded from civitai into the extension Folder.
I also closed Stable Diffusion and restarted it.

**Comment by BlafKing** [comment]
> Okay. Found a "workaround?". Tick every single categorie works fine. Just "All" is buggy.

That's odd, looking through the code, I can't see any reason why this would be the case, when 'All' is selected, it simply returns all the available options:

```py
if 'All' in folders: # Checks if all is selected
    folders = _file.get_content_choices() # Returns all the options from the list
```
So selecting every option does the exact same as selecting 'All'.

Also when this message appears:
```
The Civit-API has timed out, please try again.
The servers might be too busy or the selected model could not be found.
```
Then this likely means it was unable retrieve any models from CivitAI, which should only really happen if they are having server issues.

The error message doesn't describe the cause well though, so I'll post an update with some clearer logs describing as to what might've happened.

Also little side note, I personally recommend installing the extension through SD-WebUI's Extension tab, rather than manually dragging it into the extension folder.
This way, if you start SD-WebUI with "--update-all-extensions" then it will automatically update all your extensions upon startup!
This way you also get the latest hotfixes, instead of only major version releases on CivitAI.
