### ISSUE TITLE
[Bug]: NSFW Filtering broken

### ISSUE THREAD

**Issue by BlafKing** [BlafKing/sd-civitai-browser-plus#249]
Currently the CivitAI API has some issues with receiving and returning NSFW information about models, these issues cannot be fixed by me, since the API causes these problems.

The issues are:

* Some NSFW models are not returned as NSFW, this results in NSFW models showing up when the NSFW toggle is turned off.

* Currently the NSFW parameter has no effect on search results, so the tile count will be inaccurate when NSFW is turned off.
Additionally it may not hide all NSFW models properly, since like I said, some are not returned as NSFW and are thus not hidden.

Unfortunately nothing I can do about these issues, so this bug report can act like a little bug tracker and notification so that people know the cause!

**Comment by FilkerZero** [comment]
The browser is now broken on my installation.  I tried deleting the extension and then installing it again, and now I get errors during Automatic1111 startup and the browser tab no longer shows up in the webui.

```
*** Error loading script: civitai_api.py
    Traceback (most recent call last):
      File "D:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Automatic1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 19, in <module>
        from scripts.civitai_global import print, debug_print
    ImportError: cannot import name 'debug_print' from 'scripts.civitai_global' (D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_global.py)

---
*** Error loading script: civitai_download.py
    Traceback (most recent call last):
      File "D:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Automatic1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 15, in <module>
        from scripts.civitai_global import print, debug_print
    ImportError: cannot import name 'debug_print' from 'scripts.civitai_global' (D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_global.py)

---
*** Error loading script: civitai_file_manage.py
    Traceback (most recent call last):
      File "D:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Automatic1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 20, in <module>
        import scripts.civitai_api as _api
      File "D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 19, in <module>
        from scripts.civitai_global import print, debug_print
    ImportError: cannot import name 'debug_print' from 'scripts.civitai_global' (D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_global.py)

---
*** Error loading script: civitai_gui.py
    Traceback (most recent call last):
      File "D:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Automatic1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 10, in <module>
        from scripts.civitai_global import print, debug_print
    ImportError: cannot import name 'debug_print' from 'scripts.civitai_global' (D:\Automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_global.py)
```

**Comment by Worldgate** [comment]
Same issue with me except if i turn off the 'nsfw' check box it has an error and just gives.

CivitAI Browser+: Error: 500 Server Error: Internal Server Error for url: https://civitai.com/api/v1/models?limit=10&sort=Newest&period=AllTime&nsfw=false
Traceback (most recent call last):
  File "e:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "e:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "e:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "e:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 516, in save_model_info
    image_path = get_image_path(install_path, api_response, sub_folder)
  File "E:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 211, in get_image_path
    json_info = api_response['items'][0]
TypeError: string indices must be integers

**Comment by Worldgate** [comment]
I did get a message about them changing some of the 'ratings' to be more like the MPAA.  I got no idea why they would bother this late in the game, flagging something 'nsfw' seems to work pretty easily.

**Comment by DarthRainbows** [comment]
I think Civitai may have also changed the default behavior of the `nsfw` query param from `true` to `false`. The plugin only sets the query param to false, so this is likely why nsfw results are not returned when the setting is on. I'd make a PR to fix that, but it sounds like there is more to this for the new ratings.

**Comment by BlafKing** [comment]
Thanks for letting me know @DarthRainbows, it looks the API has had an update regarding the `nsfw` parameters.

Before it used to always return NSFW models regardless of including this parameter, but now it indeed doesn't return NSFW models unless the `nsfw` parameter has been set to `true`.

I'll make a new update that uses this new behavior to properly handle NSFW filtering again!

**Comment by BlafKing** [comment]
NSFW should now be working again in the latest commit.
Thanks for letting me know about the new API behaviour!

I'll mark this as resolved 👍🏻
