### ISSUE TITLE
[Bug]: Civitia "button" does not load info

### ISSUE THREAD

**Issue by Psokratease** [BlafKing/sd-civitai-browser-plus#342]
### Describe the bug.

Civitai emblem click opens:  "Loading model info...please wait!"  
It will Not load the model info. It goes no further.

### Steps to reproduce the problem.

1. Open SD Forge.
2. Go to txt2img.
3. Go to Lora tab.
4. Hover over any lora with mouse.
5. Left-click the Civitai emblem.

### Expected behavior

The Lora information from Civitai.com should load. Giving useful information and sample images on the particular model (Checkpoint, lora, etc.)

### System info

* Extension version: Newest/updated
* OS: Win 11 Pro
* SD-WebUI version: f2.0.1v1.10.1-previous-556-gcc378589
* Python: 3.10.6

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-556-gcc378589
Commit hash: cc378589a4ad18ea6dff4ae1a8158d19dcd5486e
Fetching updates for google_blockly...
Checking out commit for google_blockly with hash: 194520c075d750dae19d7ff51ea2a2b59338f082...
Previous HEAD position was a4dd724 1
HEAD is now at 194520c 4
CUDA 12.1
Launching Web UI with arguments:
Total VRAM 24576 MB, total RAM 65462 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
D:\Forge\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\Forge\webui\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.9.0, num models: 10
CivitAI Browser+: Aria2 RPC started
13:08:36 - ReActor - STATUS - Running v0.7.1-b1 on Device: CUDA
Loading additional modules ... done.
2024-10-07 13:08:41,901 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for D:\Forge\webui\extensions\sd-model-preview-xd\scripts\modelpreview.py
    Traceback (most recent call last):
      File "D:\Forge\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "D:\Forge\webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 1126, in on_ui_tabs
        list_all_embeddings(),
      File "D:\Forge\webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 236, in list_all_embeddings
        sd_hijack.model_hijack.embedding_db.load_textual_inversion_embeddings()
    AttributeError: 'StableDiffusionModelHijack' object has no attribute 'embedding_db'

---
Model selected: {'checkpoint_info': {'filename': 'D:\\Forge\\webui\\models\\Stable-diffusion\\jibMixPonyRealistic_v4PixelPrecision.safetensors', 'hash': 'bcc5bb14'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 49.7s (prepare environment: 13.1s, import torch: 18.3s, initialize shared: 0.5s, other imports: 1.9s, list SD models: 0.1s, load scripts: 6.6s, initialize extra networks: 0.1s, initialize google blockly: 3.3s, create ui: 3.6s, gradio launch: 2.0s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 95.83% GPU memory (23551.00 MB) to load weights, and use 4.17% GPU memory (1024.00 MB) to do matrix computation.
```

**Comment by prezofpizza** [comment]
Adding that I'm having the same issue with Forge even after the latest update.

**Comment by BlafKing** [comment]
Has been added to the to-do list, thanks for reporting!

(Might take a little while since there are a lot of bugs to patch up)

**Comment by Psokratease** [comment]
Sincere Thanks to you!

**Comment by BlafKing** [comment]
This issue should now be fixed in the latest version!

I'll mark this as resolved 👍🏻
