### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by prezofpizza** [BlafKing/sd-civitai-browser-plus#364]
### Describe the bug.

Extension does not load in Automatic111

### Steps to reproduce the problem.

Download extension
Open Automatic1111

### Expected behavior

The extension would be available.

### System info

* Extension version: Latest
* OS: Windows 11
* SD-WebUI version: Automatic 1111 Latest
* Python: 3.10

### Console logs

```Shell
*** Error executing callback ui_tabs_callback for F:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "F:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 209, in on_ui_tabs
        base_filter = gr.Dropdown(label='Base model:', multiselect=True, choices=get_base_models(), value=None, type="value", elem_id="centerText")
      File "F:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 151, in get_base_models
        json_return = _api.request_civit_api(api_url, True)
      File "F:\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 1133, in request_civit_api
        data = json.loads(response.text)
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by prezofpizza** [comment]
After a bit of tinkering I was able to eventually resolve the issue by deleting the directory and cloning the repo again.

**Comment by courtarro** [comment]
This happens when Civitai is down. The extension does not gracefully handle it when it tries to fetch `models?baseModels=GetModels`. Civitai returns an HTML error page instead of JSON, which kills the extension.
