### ISSUE TITLE
Error executing callback ui_tabs_callback for ~ \sd-civitai-browser-plus\scripts\civitai_gui.py

### ISSUE THREAD

**Issue by illuculent** [BlafKing/sd-civitai-browser-plus#370]
### Describe the bug.

Tab missing

### Steps to reproduce the problem.

Go to .... Extensions / Installed
Press .... Check for updates and Apply and restart
... No tab showing ...

### Expected behavior

Tab with options

### System info

* Extension version: 3.6.0
* OS: Windos 11
* SD-WebUI version: 1.10.0
* Python: 3.12.4

### Console logs

```Shell
[Bug]: *** Error executing callback ui_tabs_callback for D:\AI\Data\Packages\Stable Diffusion WebUI\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py     Traceback (most recent call last):       File "D:\AI\Data\Packages\Stable Diffusion WebUI\modules\script_callbacks.py", line 283, in ui_tabs_callback         res += c.callback() or []       File "D:\AI\Data\Packages\Stable Diffusion WebUI\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 209, in on_ui_tabs         base_filter = gr.Dropdown(label='Base model:', multiselect=True, choices=get_base_models(), value=None, type="value", elem_id="centerText")       File "D:\AI\Data\Packages\Stable Diffusion WebUI\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 151, in get_base_models         json_return = _api.request_civit_api(api_url, True)       File "D:\AI\Data\Packages\Stable Diffusion WebUI\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 1133, in request_civit_api         data = json.loads(response.text)       File "json\__init__.py", line 346, in loads       File "json\decoder.py", line 337, in decode       File "json\decoder.py", line 355, in raw_decode     json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)  --- [ERROR]: Config states D:\AI\Data\Packages\Stable Diffusion WebUI\config_states\civitai_subfolders.json, "created_at" does not exist
```

### Additional information

This was working at one point. Not sure when issue arose as as it updates everything automatically. Uninstalled, reinstalled, no fix.

**Comment by illuculent** [comment]
Fixed itself somehow

**Comment by courtarro** [comment]
This happens when Civitai is down. The extension does not gracefully handle it when it tries to fetch `models?baseModels=GetModels`. Civitai returns an HTML error page instead of JSON, which kills the extension.
