### ISSUE TITLE
[Bug]: No module named 'scripts.civitai_global' - It's back

### ISSUE THREAD

**Issue by Craigjw** [BlafKing/sd-civitai-browser-plus#373]
### Describe the bug.

This was supposedly fixed a while back, but it's not. ([Bug]: Browser won't load in Automatic1111 after reinstall #250)

### Steps to reproduce the problem.

Install the extension, either from Auto1111 extensions or use git clone;
git clone https://github.com/BlafKing/sd-civitai-browser-plus.git

I have tried both.
I have also tried the fix described in - [Bug]: Browser won't load in Automatic1111 after reinstall #250

### Expected behavior

The extension will load up

### System info

* Extension version: 3.6.0
* OS: Win 11
* SD-WebUI version: 1.10.1
* Python: 3.10.11

### Console logs

```Shell
*** Error loading script: civitai_api.py
    Traceback (most recent call last):
      File "H:\Auto1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Auto1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 19, in <module>
        from scripts.civitai_global import print, debug_print
    ModuleNotFoundError: No module named 'scripts.civitai_global'

---
*** Error loading script: civitai_download.py
    Traceback (most recent call last):
      File "H:\Auto1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Auto1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 15, in <module>
        from scripts.civitai_global import print, debug_print
    ModuleNotFoundError: No module named 'scripts.civitai_global'

---
*** Error loading script: civitai_file_manage.py
    Traceback (most recent call last):
      File "H:\Auto1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Auto1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 18, in <module>
        from scripts.civitai_global import print, debug_print
    ModuleNotFoundError: No module named 'scripts.civitai_global'

---
*** Error loading script: civitai_gui.py
    Traceback (most recent call last):
      File "H:\Auto1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Auto1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 10, in <module>
        from scripts.civitai_global import print, debug_print
    ModuleNotFoundError: No module named 'scripts.civitai_global'

---
*** Error loading script: settings.py
    Traceback (most recent call last):
      File "H:\Auto1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Auto1111\stable-diffusion-webui\extensions\sd-webui-lobe-theme\scripts\settings.py", line 10, in <module>
        from scripts.lib.lobe_log import LobeLog
    ModuleNotFoundError: No module named 'scripts.lib'
```

**Comment by Craigjw** [comment]
Issue was with Auto1111 installation.
