### ISSUE TITLE
[BUG] Error if changing content types between pages

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#39]
**Describe the bug**
If searching for multiple content types (like LORA and LoCon simultaneously), if a type is removed and then page change occurs, it errors out.

**To Reproduce**
1. Select more than one content type.
2. Click on "Refresh"
3. Remove a content type
4. Click "Next Page"

**Expected behavior**
The next page is loaded without the removed content type, or the list is refreshed back to the first page without that content type.

**Error**
```
Traceback (most recent call last):
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion\automatic1111\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 269, in update_next_page
    return_values = update_model_list(content_type, sort_type, period_type, use_search_term, search_term, page_count, model_name, timeOut, isNext)
  File "C:\stable-diffusion\automatic1111\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 389, in update_model_list
    for item in gl.ver_json['items']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by BlafKing** [comment]
Thanks for notifying me! I'll do some debugging to see why this is happening! 👍🏻

**Comment by BlafKing** [comment]
I've just published a hotfix that fixed this issue, thanks again for letting me know! :)
