### ISSUE TITLE
[BUG] 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by umag** [BlafKing/sd-civitai-browser-plus#41]
When trying to refresh models from civitai

```
Traceback (most recent call last):
  File "C:\Users\mag\Downloads\st-web-gui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\mag\Downloads\st-web-gui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\mag\Downloads\st-web-gui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\mag\Downloads\st-web-gui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\mag\Downloads\st-web-gui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\mag\Downloads\st-web-gui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\mag\Downloads\st-web-gui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\mag\Downloads\st-web-gui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 366, in update_model_list
    HTML = model_list_html(gl.json_data, model_dict)
  File "C:\Users\mag\Downloads\st-web-gui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 210, in model_list_html
    sha256 = json_data.get('sha256')
AttributeError: 'list' object has no attribute 'get'
```
Latest version from github of extension 
version: [v1.6.0-40-g766f553f](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/766f553f7b458a6c3aa6c8c8b71bf9f6d7224144)  •  python: 3.10.8  •  torch: 2.0.1+cu118  •  xformers: 0.0.21  •  gradio: 3.41.2

**Comment by BlafKing** [comment]
I'll close this error since I've merged your fix, thx for making the pull request for it! :)
