### ISSUE TITLE
[BUG] Bad path when downloading model, UI state in error

### ISSUE THREAD

**Issue by manchuwook** [BlafKing/sd-civitai-browser-plus#45]
**Describe the bug**
Error when downloading, doesn't change back from 'cancel download' to download after error.

**To Reproduce**
1. Go to 'Civit AI' tab
2. Click on 'Refresh'
3. Pick a model
4. Click download
5. Wait
6. Error pill will appear
7. Change tabs, refresh browser
8. Still shows 'Cancel download'

**Expected behavior**
Clicking download should write to the proper folder for the images. Instead it is not doing an exists check and appends the same thing (e.g. `models\\Stable-diffusion` `\\models\\Stable-diffusion\\`dreamshaper_8.preview.png). Here is the stack from the console

```python
Traceback (most recent call last):
  File "c:\automatic\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "c:\automatic\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "c:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\automatic\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "c:\automatic\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 399, in download_create_thread
    _file.save_preview(preview_html, path_to_new_file, install_path)
  File "c:\automatic\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 132, in save_preview
    with open(preview_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\Stable-diffusion\\models\\Stable-diffusion\\dreamshaper_8.preview.png'
```

**Screenshots**
<img width="722" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/431161/c9f0a03a-350b-4dff-a9fa-2a276cacc1e4">

**Additional context**
* Extension version: 38a70065
* OS: Windows 11 Pro
* SD version: vladomatic master branch (25/10/2023
* Python: 3.10.10
* Any Additional info
* This was a freshly checked-out install of Automatic1111 Vlad edition, only one extension was installed.

**Comment by BlafKing** [comment]
Just published an update that should now properly catch this error (v1.12.3).
Again, unfortunately unsure how the double directory got inserted, but it should now correctly catch the error and return the download button to try again.
Please let me know if this has fixed the error!

I'll close this thread for now since the bug should be fixed but please feel free to send another message here if the error still persists, I'll then be more than happy to open the issue again and look into a proper fix :)
