### ISSUE TITLE
[BUG] Unable to load model info for any model

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#49]
**Describe the bug**
All the inputs show "error" when clicking on any model card. No info loads. Looks related to the recent SHA256 change.

**To Reproduce**
1. Search for models.
2. Click on a card.

**Expected behavior**
It should load the info.

**Screenshots**
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/af82241b-816a-479f-abac-47fa3f5bf968)

**Additional context**
```
Traceback (most recent call last):
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion\automatic1111\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py", line 668, in update_models_dropdown
    (html, tags, _, DwnButton, _, filelist, filename, id, current_sha256, install_path, sub_folder) = _api.update_model_info(model_name,ret_versions['value'])
  File "C:\stable-diffusion\automatic1111\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 628, in update_model_info
    if data.get('sha256').upper() == sha256_value:
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by BlafKing** [comment]
Thanks for notifying me!
should be an easy fix by adding a try except block around it, I'll publish a quick fix for it! :)

**Comment by BlafKing** [comment]
This should now be fixed in the latest hotfix, thanks again for notifying me about it! :)
