### ISSUE TITLE
Error after downloading file

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#5]
With the latest update, I'm getting an error after downloading a file. I'm sorting by Newest.

It downloads successfully to the correct folder, then this error appears and I have to restart the UI to get the extension to start working again:

```
Traceback (most recent call last):
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion\automatic1111\extensions\sd-civitai-browser-plus\scripts\civitai-api.py", line 772, in finish_download
    return_value = update_model_list(content_type, sort_type, period_type, use_search_term, search_term, show_nsfw, delete_old_ver)
TypeError: update_model_list() missing 1 required positional argument: 'page_count'
```

I've restarted a1111 also, same issue.

**Comment by BlafKing** [comment]
Just noticed it, published a fix just now, error should be fixed 👍🏻
