### ISSUE TITLE
[Bug]: ImportError: cannot import name 'civitaimodels' from 'scripts.civitai_api'

### ISSUE THREAD

**Issue by misakitchi** [BlafKing/sd-civitai-browser-plus#91]
### Describe the bug.

I have errors at sd startup
And when i use CivitAI browser, i can search for models, but when i click on it nothing happened...

Note: i have deleted venv and reinstalled sd but same error...

### Steps to reproduce the problem.

1. Go to .... 
2. Press ....
3. ...
Just launching sd and try click on a models

### Expected behavior

View the clicked model...

### System info

* Extension version:
* OS: Winsows 10
* SD-WebUI version: 1.6.0
* Python: 3.10.12

### Console logs

```Shell
*** Error loading script: ui_civitai.py
    Traceback (most recent call last):
      File "C:\AI\SD\Bin\Auto1111\stable-diffusion-webui.new\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\SD\Bin\Auto1111\stable-diffusion-webui.new\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\SD\Bin\Auto1111\stable-diffusion-webui.new\extensions\sd-webui-civbrowser\scripts\ui_civitai.py", line 7, in <module>
        from scripts.civitai_api import civitaimodels
    ImportError: cannot import name 'civitaimodels' from 'scripts.civitai_api' (C:\AI\SD\Bin\Auto1111\stable-diffusion-webui.new\extensions\sd-civitai-browser-plus\scripts\civitai_api.py)
```

**Comment by misakitchi** [comment]
OK thanks! :)
Maybe add in description that thoses 2 extensions are incompatible?
