### ISSUE TITLE
[Bug]: Unable to download a 2nd model after downloading a model

### ISSUE THREAD

**Issue by Terroosh** [BlafKing/sd-civitai-browser-plus#95]
### Describe the bug.

After downloading a model 'Error" appears in the progress bar and you are unable to download another model until you restart the webui.

### Steps to reproduce the problem.

1. Download a model
2. After the model is downloaded "Error" appears and the download button remains stuck on "Cancel Download"

### Expected behavior

Download as usual

### System info

* Extension version: 1.15
* OS: Win 11
* SD-WebUI version: 1.6
* Python: 3.10.6

### Console logs

```Shell
CivitAI Browser+: Model saved to: K:\SD A1111\embeddings\M1RR0R53D63.pt
CivitAI Browser+: Tags saved to: K:\SD A1111\embeddings\M1RR0R53D63.json
CivitAI Browser+: Preview image saved to: K:\SD A1111\embeddings\M1RR0R53D63.preview.png
Traceback (most recent call last):
  File "K:\SD A1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "K:\SD A1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "K:\SD A1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "K:\SD A1111\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "K:\SD A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "K:\SD A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "K:\SD A1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "K:\SD A1111\extensions\sd-civitai-browser-plus\scripts\civitai_download.py", line 512, in download_create_thread
    (model, _, _) = _file.card_update(gr_components, name, list_versions, True)
  File "K:\SD A1111\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 238, in card_update
    version_choices = gr_components[0]['choices']
KeyError: 0
```

**Comment by BlafKing** [comment]
Thanks for letting me know, was a silly mistake/oversight of me, should now be fixed! :)
